#!/usr/bin/env bash
BASEDIR=$(dirname $0)
echo "basedir: ${BASEDIR}"
cd $BASEDIR

ln -s ${PWD}/.bashrc ~/.bashrc

ln -s ${PWD}/.config/awesome ~/.config/awesome

ln -s ${PWD}/.config/nvim ~/.config 

ln -s ${PWD}/.config/alacritty ~/.config/alacritty
