#!/usr/bin/env bash
BASEDIR=$(dirname $0)
echo "basedir: ${BASEDIR}"
cd $BASEDIR
add_symlink() {
    if [ ! -L ~/$1 ]; then
        ln -s ${PWD}/$1 ~/$1
    else
        echo "link for $1 already exists"
    fi
}

add_symlink .zprofile
add_symlink .zshrc
add_symlink .bashrc
add_symlink .config/awesome
add_symlink .config/nvim
add_symlink .config/alacritty
add_symlink .config/picom
add_symlink .xinitrc
add_symlink .tmux.conf
add_symlink .p10k.zsh
